# numpy 1

In [1]:
import numpy as np



### numpy 배열(N-Dimensional Array)

In [2]:
a = np.array([1,3,2,4],float)

In [3]:
a

array([1., 3., 2., 4.])

In [4]:
a.dtype, a.shape, a.ndim, a.size #데이터 타입, 행렬 모양, 몇차원, 데이터 몇갠지

(dtype('float64'), (4,), 1, 4)

In [5]:
# vector (1차원)
a = np.array([1,3,2,4],float)


In [6]:
# matrix(2차원)

b=np.array([[1,2,4],[4,3,9],[3,6,9]])
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 6, 9]])

In [7]:
b.dtype, b.shape, b.ndim, b.size

(dtype('int32'), (3, 3), 2, 9)

In [8]:
# tensor(3차원)

c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [9]:
c.dtype, c.shape, c.ndim, c.size

(dtype('int32'), (2, 3, 4), 3, 24)

In [10]:
# dtype
np.array([1,2,3,4], dtype=np.uint8)

array([1, 2, 3, 4], dtype=uint8)

In [11]:
# reshape
c.size

24

In [12]:
c.reshape(4,6) #size가 같으면 다른 다차원으로 구성 가능

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [13]:
c.reshape(3,-1) #-1은 프로그램 임의로 출력해라는 뜻

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [14]:
a.reshape(4,-1)

array([[1.],
       [3.],
       [2.],
       [4.]])

In [15]:
a.reshape(-1,4)

array([[1., 3., 2., 4.]])

In [16]:
# shape는 튜플
b.reshape(-1)

array([1, 2, 4, 4, 3, 9, 3, 6, 9])

In [17]:
b.flatten() #1차원으로 변경

array([1, 2, 4, 4, 3, 9, 3, 6, 9])

### 인덱싱과 슬라이스

In [18]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a[1][1], a[1,1], a[-1,-2]

(5, 5, 5)

In [20]:
a[1,:2]

array([4, 5])

In [21]:
a[:,1:]

array([[2, 3],
       [5, 6]])

In [22]:
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 6, 9]])

In [23]:
b[:2,1:]

array([[2, 4],
       [3, 9]])

In [24]:
b[1:,:2]

array([[4, 3],
       [3, 6]])

In [25]:
b[:2,::2]

array([[1, 4],
       [4, 9]])

# 배열 생성

In [26]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [27]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [28]:
np.arange(1,4.1,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [29]:
l=np.arange(1,4.1,0.5).tolist()  #list화
l

[1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]

In [30]:
np.arange(-2,2.01,0.02).size #-2~2까지 0.02단위로 데이터 만들기

201

In [31]:
# linear space
np.linspace(-2,2,201).size #-2~2까지 201개 데이터 만들기

201

In [33]:
#ones, zeros, empty
np.ones(shape=(10,), dtype=np.int16)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [35]:
np.ones((2,4)) #element를 모두 1로 만들어줌 2x4행렬

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.zeros(4)

array([0., 0., 0., 0.])

In [37]:
np.empty(4)

array([0., 0., 0., 0.])

In [38]:
# 정방형
np.identity(3, dtype=np.int16)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [39]:
#직사각형 모양
np.eye(N=3, M=5,dtype=np.int16)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int16)

In [56]:
a =np.eye(N=5, M=5, k=1,dtype=np.int16)
b =np.eye(N=5, M=5, k=-1,dtype=np.int16)
c=np.eye(N=5, M=5, k=0,dtype=np.int16)
a+3*b+2*c

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]], dtype=int16)

-데이터 분포에 따른 random sampling

In [42]:
np.random.randn(4) #표준 정규분포

array([ 1.01219027,  0.09946103,  1.94430152, -1.31286553])

In [44]:
np.random.uniform(3,4,4) #균등분포

array([3.09922923, 3.57289992, 3.17440183, 3.42289282])