# Numpy 2

In [1]:
import numpy as np


In [3]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
a.sum()

78

In [7]:
a.sum(axis=0) #axis 0은 세로, 1은 가로 암기

array([15, 18, 21, 24])

In [8]:
a.sum(axis=1)

array([10, 26, 42])

In [9]:
b=np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [11]:
np.sort(b) #axis=1, 오름차순 결과만 보여줌

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [13]:
b.sort() #자기 자신이 변함
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [14]:
np.sort(b, axis=0)

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [17]:
c = np.array([42,38,34,56])
np.sort(c)[::-1] #내림차순 슬라이싱으로

array([56, 42, 38, 34])

In [20]:
np.argsort(c) #인덱스값 호출 (오름차순)

array([2, 1, 0, 3], dtype=int64)

In [19]:
indices = np.argsort(c)
c[indices]

array([34, 38, 42, 56])

In [32]:
def sigmoid(x) : #많이 쓰이는 함수
    return 1. / (1+np.exp(-x))

In [31]:
xs = np.array([-10,0,10])
sigmoid(xs)

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

In [35]:
b.T #행과 열을 바꾸어줌 전치행렬

array([[ 3,  1,  1],
       [ 4,  9,  2],
       [ 5, 11,  5],
       [ 7, 12, 14]])

In [37]:
# concatenate, vstack, hstack
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [52]:
b=np.array([[5,6]])
b

array([[5, 6]])

In [53]:
np.vstack((a,b)) #2x2, 1x2를 합쳐줌(vertical로 쌓는것)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
np.hstack((a, b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [50]:
a+a #기본적으로 사칙연산 제공

array([[2, 4],
       [6, 8]])

In [48]:
a*a

array([[ 1,  4],
       [ 9, 16]])

In [49]:
a/a

array([[1., 1.],
       [1., 1.]])

### dot product

In [59]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(1,13).reshape(3,4)
np.dot(a,b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

- comparison

In [61]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [65]:
np.any(a>5), np.all(a>5) #any는 or의 개념 all 은 and의 개념

(True, False)

- logical operation

In [66]:
b = np.logical_and(a>3, a<7)
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [68]:
b = np.logical_or(a<3, a>7)
b

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

- argmax, argmin

In [71]:
np.argmax(a), np.argmin(a)

(9, 0)

### boolean & gancy index

In [74]:
b

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

In [76]:
a[b] #True값의 인덱스값 도출

array([0, 1, 2, 8, 9])

In [77]:
a[np.logical_or(a<3, a>7)]

array([0, 1, 2, 8, 9])

In [78]:
a[a>5]

array([6, 7, 8, 9])

In [79]:
a[[3,5,7,3]]

array([3, 5, 7, 3])

### 기술 통계

In [80]:
a = np.random.randn(10)
a

array([-0.11675307, -1.19986507,  0.50624032, -0.63503646,  2.11207202,
       -0.22586417,  0.33436755,  0.35510404,  0.56944322, -0.43352035])

In [82]:
a.mean(), np.mean(a) #평균

(0.12661880174656878, 0.12661880174656878)

In [84]:
a.std(), np.std(a) #표준편차

(0.8493823442133457, 0.8493823442133457)

In [85]:
a.max(), a.min()

(2.1120720170961924, -1.199865071132668)

In [87]:
# 4분위수
np.percentile(a,0)
np.percentile(a,25)


-0.38160630464922474

In [89]:
np.median(a), np.percentile(a,50)

(0.10880724164927927, 0.10880724164927927)

In [103]:
# 집단의 크기
b = np.random.randn(1000)
c = np.random.randn(100000)

In [105]:
np.mean(b), np.mean(c)

(0.04336211928288551, -0.0008850825542910073)