1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.
10 20 30 40
50 60 70 80

In [2]:
import numpy as np
a= np.arange(10,81,10).reshape(2,4)
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

2.다음    행렬과    같은   행렬이    있다.
m = np.array([[ 0,  1,  2,  3,  4],
[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
1) 이    행렬에서    값    7 을    인덱싱한다.
2) 이    행렬에서    값    14 을    인덱싱한다.
3) 이    행렬에서    배열   [6, 7] 을    슬라이싱한다.
4) 이    행렬에서    배열   [7, 12] 을    슬라이싱한다.
5) 이    행렬에서    배열   [[3, 4], [8, 9]] 을    슬라이싱한다.

In [3]:
#2-1)
m = np.array([[ 0,  1,  2,  3,  4],
[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
m[1,2]



7

In [4]:
#2-2)
m[2,4]

14

In [5]:
#2-3)
m[1,1:3]

array([6, 7])

In [6]:
#2-4)
m[1:,2]

array([ 7, 12])

In [7]:
#2-5)
m[:2,3:]

array([[3, 4],
       [8, 9]])

3.  2번의    행렬    m을    1차원    벡터    f 로    변환한    후    다음의    문제를    푸시오.
1) 이    배열에서    3의    배수를    찾아라.
2) 이    배열에서    4로    나누면    1이    남는    수를    찾아라.
3) 이    배열에서    3으로   나누면    나누어지고    4로    나누면    1이    남는    수를    찾아라

In [8]:
m = np.array([[ 0,  1,  2,  3,  4],
[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])

f= m.flatten()
#3-1)
f[3::3]

array([ 3,  6,  9, 12])

In [9]:
#3-2)
f[5::4]

array([ 5,  9, 13])

In [10]:
#3-3)
f[-2]

13

4. 값을    직접    입력하지    말고 우측의    행렬을    만드시오.

In [11]:
a =np.eye(N=5, M=5, k=1,dtype=np.int16)
b =np.eye(N=5, M=5, k=-1,dtype=np.int16)
c=np.eye(N=5, M=5, k=0,dtype=np.int16)
a+3*b+2*c

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]], dtype=int16)

5. 0에서    10까지    랜덤   실수값으로    이루어진    5 x 6 형태의    데이터    행렬을    만들고    이    데이터에 대해    다음과    같은   값을    구하시오.
1) 전체의    최댓값
2) 각    행의    합
3) 각    행의    최댓값
4) 각    열의    평균
5) 각    열의    최솟값

In [12]:
a = np.random.uniform(0,10,30).reshape(5,6)
a

array([[0.04078401, 0.85317781, 2.50562826, 0.54507001, 9.08223293,
        6.40207016],
       [9.38020441, 0.75789807, 2.14225848, 7.49619275, 8.94523614,
        2.78417969],
       [6.46424579, 0.20989075, 7.38800711, 8.4208924 , 8.6461445 ,
        3.27447297],
       [8.86603934, 3.26889324, 3.24611974, 4.60326559, 3.89370871,
        6.31125435],
       [5.03932167, 8.27367961, 7.96800489, 2.11663172, 0.18855001,
        1.90385852]])

In [13]:
#5-1)
a.max()

9.380204406786724

In [14]:
#5-2)
a.sum(axis=1)

array([19.42896318, 31.50596954, 34.40365352, 30.18928098, 25.49004642])

In [19]:
#5-3)
a.max(axis=1)

array([9.08223293, 9.38020441, 8.6461445 , 8.86603934, 8.27367961])

In [ ]:
#5-4)
a.sum(axis=0) / len(a)

array([5.6589709 , 5.88004041, 3.02340628, 4.12572623, 4.23082253,
       4.21044533])

In [20]:
#5-5)
a.min(axis=0)

array([0.04078401, 0.20989075, 2.14225848, 0.54507001, 0.18855001,
       1.90385852])

 6.다음    배열은    첫번째    행(row)에    학번, 두번째    행에   영어    성적, 세번째    행에    수학   성적을    적은 배열이다. 영어    성적을    기준으로    각    열(column)을    재정렬하시오.
array([[  1,    2,    3,    4], [ 46,   99,  100,   71], [ 81,   59,   90,  100]])

In [ ]:
a=np.array([[1,2,3,4], [46,99,100,71], [81,59,90,100]])
b= a[:,a[1].argsort(axis=0)]
b

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

7. 주사위를    100번    던지는    가상    실험을    파이썬으로    작성하고, 던져서    나오는    숫자의    평균을    구하시오.

In [ ]:
sum_1=0
for i in range(1,102):
    a = np.random.randint(0,7)
    sum_1+=a
    print(sum_1/i)

6.0
3.5
4.0
4.5
4.6
4.5
4.0
3.75
3.7777777777777777
3.8
3.8181818181818183
3.5833333333333335
3.3846153846153846
3.5714285714285716
3.6
3.625
3.764705882352941
3.7777777777777777
3.6842105263157894
3.55
3.5238095238095237
3.5
3.391304347826087
3.2916666666666665
3.2
3.076923076923077
3.111111111111111
3.107142857142857
3.0
2.966666666666667
2.870967741935484
2.84375
2.8181818181818183
2.8823529411764706
2.8857142857142857
2.8055555555555554
2.864864864864865
2.8157894736842106
2.7948717948717947
2.8
2.7560975609756095
2.7142857142857144
2.6744186046511627
2.6136363636363638
2.6222222222222222
2.6739130434782608
2.6808510638297873
2.75
2.7346938775510203
2.7
2.7058823529411766
2.730769230769231
2.6792452830188678
2.740740740740741
2.8
2.8214285714285716
2.807017543859649
2.8448275862068964
2.847457627118644
2.8333333333333335
2.80327868852459
2.806451612903226
2.857142857142857
2.84375
2.876923076923077
2.8333333333333335
2.8805970149253732
2.8529411764705883
2.8260869565217392
2.842857

8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.

In [22]:
stock = 10000 + np.random.normal(0,1,250)
stock

array([ 9999.97296902,  9998.14335554,  9997.62728509,  9999.21016686,
        9999.66379993,  9999.7148922 , 10000.24085238, 10000.55240006,
       10000.35492196,  9999.21279054,  9999.04038036,  9999.95927379,
       10002.52416526,  9998.2758198 ,  9999.69882658, 10001.05066301,
        9998.9268322 , 10000.33683343, 10000.94240315,  9998.96961555,
        9999.98957197,  9998.84772984,  9998.24647768,  9998.86775017,
        9999.69144501,  9998.46271216,  9999.15296802, 10000.34409963,
       10000.5004427 ,  9999.91694769,  9997.61482735,  9998.9630765 ,
       10001.79629647,  9999.83744502, 10000.7927738 ,  9999.10685225,
       10001.56491903, 10001.50572692,  9998.68468904, 10001.34184654,
        9999.76101488, 10001.11782253,  9999.41154064, 10000.08194011,
       10001.1215556 , 10001.17239847,  9999.51383274,  9998.9138446 ,
        9998.6617352 , 10000.97005817, 10001.01955526, 10002.97745725,
       10000.68993356,  9999.7513109 , 10002.35525494, 10001.28473805,
      